# Build and autotest script for PX4 Firmware
# http://travis-ci.org

sudo: required
dist: xenial
services:
  - docker

language: cpp

git:
  depth: 2000
  submodules: false

cache:
  ccache: true

before_install:
  # install dependencies for the coverity build (target and branch), otherwise exit early
  - if [[ "${TRAVIS_BRANCH}" = "coverity_scan" ]]; then
      sudo pip install empy jinja2 numpy toml;
      echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-;
    fi
  # use git:// to fetch instead of https://
  - git config --global url."git://".insteadOf https://

jobs:
  include:
    - stage: Tests
      name: SITL tests
      env:
        - BUILD_TARGET=tests PX4_DOCKER_REPO="px4io/px4-dev-simulation:2018-03-30"
        - BUILD_TARGET=tests_mission PX4_DOCKER_REPO="px4io/px4-dev-ros:2018-03-30"
        - BUILD_TARGET=tests_offboard PX4_DOCKER_REPO="px4io/px4-dev-ros:2018-03-30"
      script:
        - ./Tools/docker_run.sh make ${BUILD_TARGET}
    - stage: Build
      name: Firmware builds
      env:
        - BUILD_TARGET=px4fmu-v2_default
        - BUILD_TARGET=px4fmu-v2_lpe
        - BUILD_TARGET=px4fmu-v3_default
        - BUILD_TARGET=px4fmu-v3_rtps
        - BUILD_TARGET=px4fmu-v4_default
        - BUILD_TARGET=px4fmu-v4_rtps
        - BUILD_TARGET=px4fmu-v5_default
        - BUILD_TARGET=px4fmu-v5_rtps
      script:
        - ./Tools/docker_run.sh make ${BUILD_TARGET}
      deploy:
        provider: releases
        api_key: ${GITHUB_OAUTH_TOKEN}
        file_glob: true
        file:
          - build/**/*.px4
          - build/**/*.elf
        skip_cleanup: true
        on:
          tags: true
        prerelease: true

#addons:
#  coverity_scan:
#    project:
#      name: "PX4/Firmware"
#      description: "Build submitted via Travis CI"
#    notification_email: ci@px4.io
#    build_command_prepend: "make distclean"
#    build_command: "make posix_sitl_default"
#    branch_pattern: coverity_scan
