# Build and autotest script for PX4 Firmware
# http://travis-ci.org

sudo: required
dist: xenial
services:
  - docker

language: cpp

git:
  depth: 2000
  submodules: false

matrix:
  fast_finish: true
  include:
    - env: BUILD_TARGET=px4fmu-v2_default
    - env: BUILD_TARGET=px4fmu-v3_default
    - env: BUILD_TARGET=px4fmu-v4_default
  allow_failures:
    - env: BUILD_TARGET=tests_coverage

cache:
  ccache: true

before_install:
  # install dependencies for the coverity build (target and branch), otherwise exit early
  - if [[ "${TRAVIS_BRANCH}" = "coverity_scan" ]]; then
      sudo pip install empy jinja2 numpy toml;
      echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-;
    fi
  # use git:// to fetch instead of https://
  - git config --global url."git://".insteadOf https://

script:
  - ./Tools/docker_run.sh make ${BUILD_TARGET}

#addons:
#  coverity_scan:
#    project:
#      name: "PX4/Firmware"
#      description: "Build submitted via Travis CI"
#    notification_email: ci@px4.io
#    build_command_prepend: "make distclean"
#    build_command: "make posix_sitl_default"
#    branch_pattern: coverity_scan
